# Generated by Django 5.0.4 on 2024-04-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="Category",
            new_name="category",
        ),
    ]
