# Generated by Django 5.0.4 on 2024-04-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_category_recipe_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="servings_time",
            new_name="servings",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="servings_time_unit",
            new_name="servings_unit",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.category",
            ),
        ),
    ]
